export {default as Admin} from './admin'
export {default as Cart} from './cart'
export {default as Contact} from './contact'
export {default as Home} from './home'
export {default as OrderHistory} from './orderHistory'
